version: '3.1'
services:
  stats-server:
    build: stats/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_DB_URL=jdbc:postgresql://db:5432/stats-db

  stats-client:
    build: stats/client
    container_name: stats-client
    ports:
      - "6060:6060"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - EWM_DB_URL=jdbc:postgresql://db:5642/ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6455:5642"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
